CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_RGB_UNDERGLOW=y  # Enable this!
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_WS2812_STRIP=y  # Add this for WS2812 LEDs

CONFIG_ZMK_KEYBOARD_NAME="qlaviatoora"
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_IDLE_TIMEOUT_SEC=-1
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# Remove backlight - Aurora Lily58 doesn't have single-color backlight
# CONFIG_ZMK_BACKLIGHT=y
# CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y